site_name: CMU Optimal Control 16-745
nav:
  - Home: index.md
  - Background: background.md
  # - Course Notes:
  #   - Home: course_notes/notes_home.md
  #   - Dynamics:
  #     - course_notes/dynamics/lec1.md
  #     - course_notes/dynamics/lec2.md
  #   - Optimization:
  #     - course_notes/optimization/lec3.md 
  #     - course_notes/optimization/lec4.md
  # - Syllabus: syllabus.md 
  - Lectures: lectures.md 
  - Recitations: recitations.md
  - Office Hours: office_hours.md
  - Homeworks: homeworks.md
  - Quizzes: quizzes.md
  - Piazza: piazza.md
  # - Homeworks: homeworks/homeworks_home.md

  # - Quizzes: quizzes.md


theme:
  name: material
  palette:
    primary: custom
  features:
    - navigation.sections  # Sections are included in the navigation on the left.
    - navigation.expand
    - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
    - header.autohide  # header disappears as you scroll
  icon:
    logo: "material/rocket-outline"  # Equinox logo in top left
  favicon: "images/favicon.ico"
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

repo_url: https://github.com/Optimal-Control-16-745

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
